#!/usr/bin/env sh
#
## DESCRIPTION: Creates a nice ISO-8601 timestamp for usage in filenames, this
##              is a built in format in some implementations of date.
##
## AUTHOR: Alexander Hultnér <ahultner+ghts@gmail.com>
##
## USAGE: cp file.ext backup/file.$(timestamp -u).ext
##        vi notes-$(timestamp).txt
##        timestamp
##
## OPTIONS:
##   -u      Display or set the date in UTC (Coordinated Universal) time.
##

date $1 +"%Y-%m-%dT%H:%M:%S%z" | sed -e 's/+0000$/Z/g'  
